[package]
name = "rust-riscv"
version = "0.1.0"
authors = ["SoyaOhnishi <soya.ohnishi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitwise = { path = "/Users/soya/Documents/src/rust/bitwise" }